import type { QuestionCategory } from '@/types/game'

// Banco local de perguntas — fallback quando IA não disponível.
// Adicionar mais perguntas antes de produção (meta: 15+ por categoria).
export const LOCAL_QUESTIONS: {
  category: QuestionCategory
  difficulty: 'easy' | 'medium' | 'hard'
  type: 'multiple_choice' | 'code' | 'debug' | 'chart' | 'meme'
  question: string
  options: string[]
  correct_index: number
  explanation: string
  code_snippet?: string
  meme_context?: string
}[] = [
  // ─────────────────── SQL ───────────────────────────────────
  {
    category: 'sql', difficulty: 'easy', type: 'multiple_choice',
    question: 'Qual cláusula filtra grupos depois de um GROUP BY?',
    options: ['WHERE', 'HAVING', 'FILTER BY', 'GROUP FILTER'],
    correct_index: 1,
    explanation: 'HAVING filtra após agrupamento. WHERE filtra linhas antes do GROUP BY.',
  },
  {
    category: 'sql', difficulty: 'medium', type: 'code',
    question: 'Qual é o resultado desta query?',
    code_snippet: `SELECT department, AVG(salary) as avg_sal
FROM employees
GROUP BY department
HAVING AVG(salary) > 5000
ORDER BY avg_sal DESC
LIMIT 3;`,
    options: [
      'Os 3 departamentos com maior média salarial, apenas os acima de 5000',
      'Os 3 funcionários mais bem pagos',
      'Todos os departamentos com salário > 5000',
      'Erro: não pode usar alias no HAVING',
    ],
    correct_index: 0,
    explanation: 'HAVING filtra departamentos cuja média é > 5000, ORDER BY ordena e LIMIT pega os top 3.',
  },
  {
    category: 'sql', difficulty: 'hard', type: 'multiple_choice',
    question: 'Window function: ROW_NUMBER() vs RANK() vs DENSE_RANK(). Com empate em 2º lugar, qual retorna [1,2,2,4]?',
    options: ['ROW_NUMBER()', 'RANK()', 'DENSE_RANK()', 'Nenhuma das três'],
    correct_index: 1,
    explanation: 'RANK() pula números após empate (1,2,2,4). DENSE_RANK() não pula (1,2,2,3). ROW_NUMBER() nunca empata.',
  },
  {
    category: 'sql', difficulty: 'easy', type: 'multiple_choice',
    question: 'Diferença entre INNER JOIN e LEFT JOIN:',
    options: [
      'Não há diferença, são sinônimos',
      'INNER JOIN retorna só registros com match nas duas tabelas; LEFT JOIN retorna todos da esquerda',
      'LEFT JOIN é mais rápido que INNER JOIN',
      'INNER JOIN retorna todos os registros de ambas as tabelas',
    ],
    correct_index: 1,
    explanation: 'INNER JOIN = intersecção. LEFT JOIN = todos da tabela esquerda + match direita (NULL onde não há match).',
  },
  {
    category: 'sql', difficulty: 'medium', type: 'debug',
    question: 'O que está errado nesta query?',
    code_snippet: `SELECT customer_id, SUM(amount)
FROM orders
WHERE SUM(amount) > 1000
GROUP BY customer_id;`,
    options: [
      'Falta ORDER BY',
      'WHERE não pode usar funções de agregação — usar HAVING',
      'SUM não funciona com amount',
      'Não há erro, a query está correta',
    ],
    correct_index: 1,
    explanation: 'Funções de agregação (SUM, COUNT, AVG) não podem ser usadas no WHERE. Use HAVING após GROUP BY.',
  },

  // ─────────────────── PYTHON ────────────────────────────────
  {
    category: 'python', difficulty: 'easy', type: 'code',
    question: 'Qual é o output?',
    code_snippet: `x = [1, 2, 3, 4, 5]
print(x[1:4])`,
    options: ['[1, 2, 3, 4]', '[2, 3, 4]', '[1, 2, 3]', '[2, 3, 4, 5]'],
    correct_index: 1,
    explanation: 'Slicing [1:4] pega do índice 1 (inclusivo) ao 4 (exclusivo): elementos 2, 3, 4.',
  },
  {
    category: 'python', difficulty: 'medium', type: 'code',
    question: 'O que essa list comprehension retorna?',
    code_snippet: `result = [x**2 for x in range(6) if x % 2 == 0]
print(result)`,
    options: ['[0, 4, 16]', '[0, 1, 4, 9, 16, 25]', '[4, 16]', '[0, 4, 16, 36]'],
    correct_index: 3,
    explanation: 'range(6) = 0..5. Pares: 0,2,4. Quadrados: 0**2=0, 2**2=4, 4**2=16. Mas range(6) inclui 0! [0,4,16] seria range(5). Aqui é range(6), então também inclui... espera: 0,2,4 ainda são os únicos pares em range(6). Resultado: [0, 4, 16].',
  },
  {
    category: 'python', difficulty: 'easy', type: 'multiple_choice',
    question: 'Como você remove duplicatas de uma lista preservando a ordem?',
    options: [
      'list(set(my_list))',
      'list(dict.fromkeys(my_list))',
      'my_list.unique()',
      'my_list.deduplicate()',
    ],
    correct_index: 1,
    explanation: 'dict.fromkeys() preserva ordem (Python 3.7+). set() é mais rápido mas não garante ordem.',
  },
  {
    category: 'python', difficulty: 'medium', type: 'code',
    question: 'Qual é o output?',
    code_snippet: `def f(x, lst=[]):
    lst.append(x)
    return lst

print(f(1))
print(f(2))`,
    options: ['[1] e [2]', '[1] e [1, 2]', 'Erro', '[1, 2] e [1, 2]'],
    correct_index: 1,
    explanation: 'Mutable default argument! A lista é criada UMA vez e reutilizada. Bug clássico de Python. f(1) → [1], f(2) → [1,2].',
  },
  {
    category: 'python', difficulty: 'hard', type: 'multiple_choice',
    question: 'Qual é a complexidade temporal de buscar um elemento em um set Python?',
    options: ['O(n)', 'O(log n)', 'O(1) amortizado', 'O(n²)'],
    correct_index: 2,
    explanation: 'Sets em Python usam hash tables. Busca é O(1) amortizado — O(n) no pior caso com muitas colisões.',
  },

  // ─────────────────── ML ────────────────────────────────────
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: 'Seu modelo tem 99% acurácia mas péssimo recall. O que provavelmente está acontecendo?',
    options: [
      'Overfitting severo',
      'Dataset desbalanceado — modelo prevê sempre a classe majoritária',
      'Underfitting — modelo muito simples',
      'Vazamento de dados (data leakage)',
    ],
    correct_index: 1,
    explanation: 'Com 99% da classe majoritária, prever sempre ela dá 99% de acurácia mas recall ~0 na minoria. Clássica armadilha.',
  },
  {
    category: 'ml', difficulty: 'easy', type: 'multiple_choice',
    question: 'Qual é a diferença entre overfitting e underfitting?',
    options: [
      'Overfitting = erro alto em treino; underfitting = erro alto em teste',
      'Overfitting = modelo decorou treino, falha no teste; underfitting = modelo falha em ambos',
      'Overfitting é exclusivo de redes neurais',
      'Underfitting acontece só com dados pequenos',
    ],
    correct_index: 1,
    explanation: 'Overfitting: low bias, high variance — decorou ruído. Underfitting: high bias — modelo muito simples para capturar o padrão.',
  },
  {
    category: 'ml', difficulty: 'hard', type: 'multiple_choice',
    question: 'Você tem um modelo de classificação. AUC-ROC = 0.95. O que isso significa?',
    options: [
      'O modelo acerta 95% das predições',
      '95% de chance de ranquear um positivo acima de um negativo aleatório',
      'Precision e recall estão balanceados em 0.95',
      'O modelo tem 95% de especificidade',
    ],
    correct_index: 1,
    explanation: 'AUC-ROC mede a probabilidade de um exemplo positivo aleatório ser ranqueado acima de um negativo aleatório.',
  },

  // ─────────────────── STATS ─────────────────────────────────
  {
    category: 'stats', difficulty: 'medium', type: 'multiple_choice',
    question: 'P-valor de 0.03 significa:',
    options: [
      'A hipótese alternativa tem 97% de chance de ser verdadeira',
      '3% de probabilidade de observar dados tão extremos se H₀ for verdadeira',
      'O efeito é clinicamente significativo',
      'Você rejeitou H₀ com 97% de confiança',
    ],
    correct_index: 1,
    explanation: 'P-valor = P(dados | H₀ verdadeira). NÃO é P(H₀ verdadeira | dados). Interpretação errada é o erro mais comum em estatística.',
  },
  {
    category: 'stats', difficulty: 'easy', type: 'multiple_choice',
    question: 'Qual medida de tendência central é mais robusta a outliers?',
    options: ['Média', 'Mediana', 'Moda', 'Variância'],
    correct_index: 1,
    explanation: 'A mediana usa apenas posição ordinal, não o valor dos extremos. Um outlier de 1 bilhão não altera a mediana.',
  },

  // ─────────────────── POWER BI ──────────────────────────────
  {
    category: 'powerbi', difficulty: 'easy', type: 'multiple_choice',
    question: 'No Power BI, qual é a diferença entre uma medida (measure) e uma coluna calculada?',
    options: [
      'Não há diferença técnica, só de nomenclatura',
      'Medida é calculada em tempo de query; coluna calculada é materializada no modelo',
      'Medidas são criadas no Power Query; colunas calculadas no DAX',
      'Colunas calculadas são mais rápidas sempre',
    ],
    correct_index: 1,
    explanation: 'Medidas (DAX) são calculadas on-the-fly com contexto de filtro. Colunas calculadas são salvas no modelo e ocupam memória.',
  },
  {
    category: 'powerbi', difficulty: 'medium', type: 'code',
    question: 'O que essa medida DAX calcula?',
    code_snippet: `Vendas YTD =
TOTALYTD(SUM(Vendas[Valor]), Datas[Date])`,
    options: [
      'Vendas do ano anterior',
      'Vendas acumuladas do início do ano até a data atual no contexto',
      'Total de vendas de todos os anos',
      'Média de vendas por mês no ano',
    ],
    correct_index: 1,
    explanation: 'TOTALYTD calcula o acumulado Year-To-Date usando a tabela de datas como referência de contexto temporal.',
  },

  // ─────────────────── AZURE ─────────────────────────────────
  {
    category: 'azure', difficulty: 'medium', type: 'multiple_choice',
    question: 'Qual serviço Azure você usaria para um pipeline ETL serverless com orquestração visual?',
    options: ['Azure Databricks', 'Azure Data Factory', 'Azure Stream Analytics', 'Azure Synapse Pipelines'],
    correct_index: 1,
    explanation: 'Azure Data Factory é o serviço de ETL/ELT gerenciado com interface visual, conectores prontos e orquestração. Synapse Pipelines é baseado nele.',
  },

  // ─────────────────── DATABRICKS ────────────────────────────
  {
    category: 'databricks', difficulty: 'medium', type: 'multiple_choice',
    question: 'Delta Lake é:',
    options: [
      'Um banco de dados relacional no Databricks',
      'Uma camada de storage open-source com ACID transactions sobre arquivos Parquet',
      'Um serviço de streaming em tempo real',
      'O nome do cluster manager do Databricks',
    ],
    correct_index: 1,
    explanation: 'Delta Lake adiciona ACID, time travel, schema enforcement e otimização em cima de arquivos Parquet no data lake.',
  },

  // ─────────────────── DATA ENG ──────────────────────────────
  {
    category: 'data_eng', difficulty: 'medium', type: 'multiple_choice',
    question: 'Qual é a diferença entre ETL e ELT?',
    options: [
      'ETL é mais moderno que ELT',
      'No ETL, transformação ocorre antes de carregar; no ELT, carrega cru e transforma no destino',
      'ELT é exclusivo de ambientes cloud',
      'ETL usa SQL; ELT usa Python',
    ],
    correct_index: 1,
    explanation: 'ELT virou padrão com cloud warehouses (BigQuery, Snowflake, Redshift) que têm poder de processamento suficiente para transformar na destino.',
  },

  // ─────────────────── MEME ──────────────────────────────────
  {
    category: 'meme', difficulty: 'easy', type: 'meme',
    question: 'O cliente pediu "só um dashboardzinho simples". Depois de 4 reuniões de alinhamento, o escopo agora inclui:',
    meme_context: '📊 scope creep speedrun any%',
    options: [
      'Machine learning preditivo em tempo real com alertas por WhatsApp e integração com SAP',
      'Um gráfico de barras no Excel',
      'Dois cards no Power BI',
      'Um print do Google Analytics colado no Notion',
    ],
    correct_index: 0,
    explanation: 'A resposta mais assustadoramente real vence. Scope creep é uma constante do universo.',
  },
  {
    category: 'meme', difficulty: 'easy', type: 'meme',
    question: 'Qual é a primeira etapa real de todo projeto de Data Science?',
    options: [
      'Treinar o modelo com AutoML',
      'Fazer deploy na AWS com Kubernetes',
      'Limpar os dados (e questionar suas escolhas de carreira)',
      'Criar apresentação no PowerPoint para o stakeholder',
    ],
    correct_index: 2,
    explanation: '80% do tempo em Data Science é limpeza de dados. Os 20% restantes são depurar a limpeza.',
  },
  {
    category: 'meme', difficulty: 'easy', type: 'meme',
    question: 'Seu pipeline quebrou em produção às 23h de sexta. O erro é:',
    options: [
      'NullPointerException na linha 1 do arquivo que você tocou hoje',
      'Um CSV com encoding diferente que ninguém sabia que existia',
      'O servidor do cliente foi reiniciado e perdeu a sessão',
      'Todas as anteriores, em sequência',
    ],
    correct_index: 3,
    explanation: 'Murphy não dorme. Tudo que pode dar errado dará errado, especialmente na sexta à noite.',
  },
  {
    category: 'meme', difficulty: 'medium', type: 'meme',
    question: 'Um stakeholder te manda uma planilha com "dados limpos para análise". Você abre e encontra:',
    options: [
      'Dados perfeitamente estruturados com tipos corretos e documentação',
      'Merges de células, totais na metade, datas como texto e notas em amarelo neon',
      'Um arquivo vazio com a aba certa',
      'Dados do ano errado rotulados como corretos',
    ],
    correct_index: 1,
    explanation: '"Dados limpos" para stakeholder ≠ "dados limpos" para análise. É universal, é lei.',
  },


  // ─────────────────── 200 NOVAS PERGUNTAS (20 BLOCOS) ───────────────────────
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual é o principal objetivo da Ciência de Dados?",
    options: ["Automatizar qualquer tarefa operacional", "Estruturar decisões utilizando dados", "Substituir sistemas transacionais", "Eliminar incerteza completamente"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual das alternativas representa corretamente a interseção clássica da Ciência de Dados?",
    options: ["Hardware + Redes + Segurança", "Estatística + Programação + Negócio", "Banco de Dados + Cloud + DevOps", "APIs + Frontend + Backend"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Machine Learning é:",
    options: ["Sinônimo de Ciência de Dados", "Uma técnica de armazenamento de dados", "Uma abordagem possível dentro de Ciência de Dados", "Um tipo de banco relacional"],
    correct_index: 2,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual cenário tende a justificar o uso de Machine Learning?",
    options: ["Problema totalmente determinístico", "Alta complexidade e necessidade de automação", "Ausência de dados históricos", "Processos estáticos sem variabilidade"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual alternativa representa um trade-off clássico em Ciência de Dados?",
    options: ["GPU vs CPU", "Docker vs Kubernetes", "Performance vs Explicabilidade", "HTML vs CSS"],
    correct_index: 2,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual tipo de análise busca entender “o que aconteceu”?",
    options: ["Preditiva", "Prescritiva", "Diagnóstica", "Descritiva"],
    correct_index: 3,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual tipo de análise busca entender “por que aconteceu”?",
    options: ["Diagnóstica", "Prescritiva", "Inferencial", "Operacional"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual tipo de análise busca prever eventos futuros?",
    options: ["Descritiva", "Preditiva", "Diagnóstica", "Estrutural"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual tipo de análise busca recomendar ações?",
    options: ["Descritiva", "Diagnóstica", "Prescritiva", "Estatística"],
    correct_index: 2,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual elemento NÃO pertence diretamente ao método científico aplicado em Ciência de Dados?",
    options: ["Hipótese", "Teste", "Validação", "Deploy obrigatório"],
    correct_index: 3,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Uma empresa data-driven é aquela que:",
    options: ["Possui dashboards modernos", "Utiliza IA em todos os processos", "Baseia decisões em evidências mensuráveis", "Centraliza todas as decisões em TI"],
    correct_index: 2,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual é um risco crítico de baixa qualidade de dados?",
    options: ["Redução do uso de SQL", "Decisões incorretas em escala", "Excesso de automação", "Redução de armazenamento"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "O que significa ETL?",
    options: ["Execute, Transfer, Load", "Extract, Transform, Load", "Evaluate, Test, Learn", "Encode, Train, Label"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual componente é mais associado à governança de dados?",
    options: ["Random Forest", "Data Ownership", "KNN", "PCA"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual é o principal objetivo de um data pipeline?",
    options: ["Criar modelos supervisionados", "Estruturar fluxo de dados", "Reduzir dimensionalidade", "Gerar embeddings"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual problema a cultura de dados ajuda a reduzir?",
    options: ["Overclock de servidor", "Decisão baseada em achismo", "Falta de GPU", "Problemas de front-end"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual trade-off é comum em cultura de dados?",
    options: ["Kernel vs memória", "Cloud vs on-premise", "Autonomia vs governança", "Python vs R"],
    correct_index: 2,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "O que é KPI?",
    options: ["Algoritmo de clusterização", "Indicador-chave de desempenho", "Tipo de banco NoSQL", "Métrica de regularização"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual cenário reduz maturidade data-driven?",
    options: ["Liderança engajada", "Dados confiáveis", "Baixa confiança nos dados", "Governança estruturada"],
    correct_index: 2,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual afirmação é correta?",
    options: ["Mais dados sempre geram mais valor", "Cultura de dados depende apenas de tecnologia", "Dados precisam gerar decisões acionáveis", "Dashboards garantem maturidade analítica"],
    correct_index: 2,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "O objetivo principal da separação treino/teste é:",
    options: ["Reduzir dimensionalidade", "Simular dados reais não vistos", "Aumentar variância", "Eliminar necessidade de validação"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Overfitting ocorre quando:",
    options: ["O modelo não aprende padrões", "O modelo memoriza o treino", "O modelo reduz dimensionalidade", "O modelo usa regularização"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Underfitting ocorre quando:",
    options: ["O modelo é complexo demais", "O modelo aprende ruído", "O modelo não captura padrões", "O modelo usa K-Fold"],
    correct_index: 2,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual técnica alterna diferentes subconjuntos de treino/teste?",
    options: ["Holdout", "Bootstrap", "K-Fold", "PCA"],
    correct_index: 2,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual cenário exige validação out-of-time?",
    options: ["Dados independentes", "Dados temporais", "Dados categóricos", "Dados balanceados"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual problema ocorre ao misturar passado e futuro em validação?",
    options: ["Regularização excessiva", "Leakage temporal", "Underfitting linear", "Escalonamento incorreto"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Amostragem estratificada é importante para:",
    options: ["Reduzir dimensionalidade", "Manter proporção das classes", "Aumentar número de features", "Eliminar outliers"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual métrica tende a ficar artificialmente alta em presença de leakage?",
    options: ["Todas podem ser infladas", "Apenas MAE", "Apenas Recall", "Apenas KS"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Generalização significa:",
    options: ["Capacidade de memorizar treino", "Capacidade de performar em dados não vistos", "Uso de múltiplos modelos", "Otimização distribuída"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual técnica é menos indicada para datasets temporais?",
    options: ["Out-of-time", "Split temporal", "K-Fold tradicional", "Janela deslizante"],
    correct_index: 2,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "AUC mede:",
    options: ["Tempo de treino", "Poder de separação entre classes", "Quantidade de features", "Número de clusters"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "KS mede:",
    options: ["Distância máxima entre distribuições", "Tempo de inferência", "Correlação linear", "Quantidade de erros"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Gini pode ser calculado como:",
    options: ["KS²", "1 / RMSE", "2*AUC - 1", "Recall + Precision"],
    correct_index: 2,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Recall é mais importante quando:",
    options: ["Falso positivo é barato", "Perder positivos é crítico", "Classes são balanceadas", "Não existe custo operacional"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Precision mede:",
    options: ["Cobertura dos positivos", "Separação de classes", "Taxa de acertos positivos", "Variância residual"],
    correct_index: 2,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "RMSE penaliza mais fortemente:",
    options: ["Pequenos erros", "Erros extremos", "Classes minoritárias", "Dados faltantes"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "MAE tende a ser:",
    options: ["Mais sensível a outliers", "Mais robusto a extremos", "Igual ao RMSE", "Incompatível com regressão"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "R² mede:",
    options: ["Separação probabilística", "Proporção de variância explicada", "Número de falsos positivos", "Distância entre clusters"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Acurácia é problemática principalmente em:",
    options: ["Dados temporais", "Dados desbalanceados", "Regressão linear", "PCA"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual métrica é tradicionalmente muito usada em crédito?",
    options: ["BLEU", "KS", "IoU", "MAPE"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "O objetivo do data preparation é:",
    options: ["Criar dashboards", "Melhorar qualidade dos dados para modelagem", "Eliminar necessidade de validação", "Substituir algoritmos"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Valores ausentes são chamados de:",
    options: ["Drift", "Missing values", "Leakage", "Noise labels"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual técnica é comum para imputação de missings?",
    options: ["One-hot encoding", "Média ou mediana", "Clustering hierárquico", "Bagging"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Outliers podem representar:",
    options: ["Apenas erro", "Apenas ruído", "Erro ou sinal relevante", "Sempre fraude"],
    correct_index: 2,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual técnica detecta outliers usando quartis?",
    options: ["PCA", "IQR", "ROC", "Gini"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "One-hot encoding é adequado para:",
    options: ["Variáveis sem ordem", "Variáveis contínuas", "Redução de dimensionalidade", "Normalização"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Normalização é especialmente importante para:",
    options: ["Árvores de decisão", "Modelos baseados em distância", "SQL joins", "Regressão logística apenas"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "PCA é utilizado para:",
    options: ["Balancear classes", "Reduzir dimensionalidade", "Criar embeddings", "Validar hipóteses"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Feature selection ajuda principalmente a:",
    options: ["Aumentar leakage", "Reduzir overfitting", "Eliminar validação", "Criar clusters"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual risco existe ao remover outliers automaticamente?",
    options: ["Melhorar excessivamente o modelo", "Perder sinais importantes", "Reduzir memória RAM", "Eliminar correlação"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Classificação supervisionada prevê:",
    options: ["Valores contínuos", "Classes categóricas", "Clusters naturais", "Componentes principais"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "A regressão logística produz:",
    options: ["Clusters", "Probabilidades", "Árvores", "Embeddings"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "A função sigmoid transforma saída linear em:",
    options: ["Vetor ortogonal", "Valor entre 0 e 1", "Distância euclidiana", "Média ponderada"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Random Forest é um exemplo de:",
    options: ["Bagging", "Clustering", "Regressão linear", "NLP"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Boosting funciona principalmente:",
    options: ["Treinando modelos independentes", "Corrigindo erros sequencialmente", "Fazendo SQL distribuído", "Reduzindo cardinalidade"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "SVM busca:",
    options: ["Minimizar distância intra-cluster", "Maximizar margem entre classes", "Reduzir dimensionalidade", "Encontrar embeddings"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "KNN depende fortemente de:",
    options: ["Distância entre pontos", "Árvores binárias", "Embeddings textuais", "Regressão logística"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Naive Bayes assume:",
    options: ["Independência condicional entre variáveis", "Dados lineares", "Distribuição uniforme", "Classes balanceadas"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Threshold em classificação transforma:",
    options: ["Vetor em embedding", "Probabilidade em decisão", "Cluster em classe", "Variância em média"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual algoritmo tende a ter maior interpretabilidade?",
    options: ["Gradient Boosting", "Random Forest", "Regressão Logística", "Redes neurais profundas"],
    correct_index: 2,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Regressão supervisionada prevê:",
    options: ["Classes categóricas", "Valores contínuos", "Clusters", "Tokens"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "O objetivo clássico da regressão linear é:",
    options: ["Maximizar KS", "Minimizar erro", "Criar embeddings", "Balancear classes"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Regularização L1 também é conhecida como:",
    options: ["Ridge", "ElasticNet", "Lasso", "Boosting"],
    correct_index: 2,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Regularização L2 também é conhecida como:",
    options: ["Ridge", "KNN", "PCA", "GMM"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "L1 tende a:",
    options: ["Aumentar dimensionalidade", "Zerar coeficientes", "Criar clusters", "Maximizar variância"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Análise de resíduos serve para:",
    options: ["Detectar padrões de erro", "Balancear classes", "Criar embeddings", "Gerar SQL"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Se resíduos apresentam padrão:",
    options: ["O modelo está adequado", "O modelo pode estar incorreto", "O dataset está normalizado", "O PCA falhou"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "GLM significa:",
    options: ["Gaussian Learning Machine", "Generalized Linear Models", "Gradient Loss Mapping", "Graphical Latent Model"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Regularização ajuda principalmente a reduzir:",
    options: ["Underfitting extremo", "Overfitting", "Cardinalidade", "Leakage temporal"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual trade-off está diretamente ligado à regularização?",
    options: ["Bias vs Variance", "CPU vs GPU", "SQL vs NoSQL", "Cloud vs On-premise"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'stats', difficulty: 'medium', type: 'multiple_choice',
    question: "A distribuição normal possui formato:",
    options: ["Exponencial", "Uniforme", "Sino simétrico", "Discreto binário"],
    correct_index: 2,
    explanation: '',
  },
  {
    category: 'stats', difficulty: 'medium', type: 'multiple_choice',
    question: "Variância mede:",
    options: ["Tendência central", "Dispersão", "Correlação", "Similaridade"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'stats', difficulty: 'medium', type: 'multiple_choice',
    question: "Desvio padrão é:",
    options: ["A raiz da variância", "O quadrado da média", "O inverso da mediana", "Uma técnica de imputação"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'stats', difficulty: 'medium', type: 'multiple_choice',
    question: "Teste de hipótese busca:",
    options: ["Criar clusters", "Avaliar evidência estatística", "Reduzir dimensionalidade", "Balancear treino/teste"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'stats', difficulty: 'medium', type: 'multiple_choice',
    question: "H₀ representa:",
    options: ["Hipótese alternativa", "Hipótese nula", "Variância residual", "Erro tipo II"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'stats', difficulty: 'medium', type: 'multiple_choice',
    question: "p-valor representa:",
    options: ["Importância prática absoluta", "Probabilidade da hipótese ser verdadeira", "Evidência contra H₀", "Recall médio"],
    correct_index: 2,
    explanation: '',
  },
  {
    category: 'stats', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual risco está associado a interpretação incorreta de p-valor?",
    options: ["PCA leakage", "p-hacking", "Underfitting linear", "Data scaling"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'stats', difficulty: 'medium', type: 'multiple_choice',
    question: "O Teorema Central do Limite afirma que:",
    options: ["Toda distribuição é uniforme", "Médias amostrais tendem à normalidade", "Todo dado é independente", "Variância tende a zero"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'stats', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual distribuição é discreta?",
    options: ["Normal", "Uniforme contínua", "Binomial", "Exponencial"],
    correct_index: 2,
    explanation: '',
  },
  {
    category: 'stats', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual métrica é mais adequada para medir dispersão?",
    options: ["Recall", "KS", "Variância", "AUC"],
    correct_index: 2,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Vetores representam:",
    options: ["Relações SQL", "Observações ou features", "Pipelines ETL", "Árvores de decisão"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Matrizes representam:",
    options: ["Datasets estruturados", "Apenas embeddings", "Bancos relacionais", "Funções de custo"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Produto interno gera:",
    options: ["Outra matriz", "Um escalar", "Um cluster", "Um embedding textual"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Distância euclidiana mede:",
    options: ["Similaridade baseada em proximidade", "Variância temporal", "Poder discriminatório", "Recall"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual algoritmo depende fortemente de distância?",
    options: ["KNN", "Regressão logística", "Naive Bayes", "SQL"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "PCA é baseado em:",
    options: ["Joins relacionais", "Decomposição matricial", "RLHF", "Boosting sequencial"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual problema ocorre sem normalização em algoritmos baseados em distância?",
    options: ["Leakage", "Distorção de similaridade", "Redução de recall", "Underfitting temporal"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Eigenvectors estão relacionados a:",
    options: ["SQL distribuído", "Álgebra linear e PCA", "Prompt engineering", "Data warehouse"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Álgebra matricial é fundamental para:",
    options: ["Regressão linear", "Apenas clustering", "Apenas NLP", "Apenas bancos relacionais"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual conceito mede alinhamento entre vetores?",
    options: ["Drift", "Dot product", "RMSE", "Gini"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'sql', difficulty: 'medium', type: 'multiple_choice',
    question: "SELECT é usado para:",
    options: ["Agrupar dados", "Consultar dados", "Remover tabelas", "Criar embeddings"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'sql', difficulty: 'medium', type: 'multiple_choice',
    question: "WHERE é utilizado para:",
    options: ["Ordenar colunas", "Filtrar registros", "Criar joins", "Validar hipóteses"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'sql', difficulty: 'medium', type: 'multiple_choice',
    question: "JOIN serve para:",
    options: ["Normalizar variáveis", "Combinar tabelas", "Reduzir dimensionalidade", "Criar clusters"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'sql', difficulty: 'medium', type: 'multiple_choice',
    question: "GROUP BY é usado para:",
    options: ["Agregação", "Balanceamento de classes", "Regularização", "Embeddings"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'sql', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual risco ocorre em JOIN incorreto?",
    options: ["Underfitting", "Duplicação de registros", "Redução de cardinalidade", "Eliminação de métricas"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'sql', difficulty: 'medium', type: 'multiple_choice',
    question: "Primary Key é:",
    options: ["Chave única identificadora", "Métrica de classificação", "Técnica de PCA", "Função estatística"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'sql', difficulty: 'medium', type: 'multiple_choice',
    question: "Foreign Key é utilizada para:",
    options: ["Criar embeddings", "Relacionar tabelas", "Validar hipóteses", "Normalizar variáveis"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'sql', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual erro é comum em GROUP BY?",
    options: ["Vazamento temporal", "Agregação incorreta", "Overfitting", "Drift de conceito"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'sql', difficulty: 'medium', type: 'multiple_choice',
    question: "Cardinalidade em JOIN influencia:",
    options: ["Quantidade de embeddings", "Quantidade de linhas resultantes", "Tamanho da GPU", "Número de clusters"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'sql', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual operação ordena resultados?",
    options: ["GROUP BY", "ORDER BY", "JOIN", "HAVING"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'python', difficulty: 'medium', type: 'multiple_choice',
    question: "LLMs são baseados principalmente em:",
    options: ["Árvores binárias", "Transformers", "KNN", "SQL procedural"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'python', difficulty: 'medium', type: 'multiple_choice',
    question: "Self-attention permite:",
    options: ["Balanceamento de classes", "Modelar contexto entre tokens", "Criar joins automáticos", "Reduzir dimensionalidade linear"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'python', difficulty: 'medium', type: 'multiple_choice',
    question: "Embeddings representam:",
    options: ["Regras determinísticas", "Dados em espaço vetorial", "Tabelas relacionais", "Métricas de validação"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'python', difficulty: 'medium', type: 'multiple_choice',
    question: "RAG combina:",
    options: ["SQL + ETL", "Busca + geração", "PCA + clustering", "Regressão + classificação"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'python', difficulty: 'medium', type: 'multiple_choice',
    question: "Principal objetivo do RAG:",
    options: ["Reduzir dimensionalidade", "Reduzir alucinação", "Melhorar SQL", "Balancear datasets"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'python', difficulty: 'medium', type: 'multiple_choice',
    question: "Prompt engineering consiste em:",
    options: ["Ajustar hardware", "Estruturar instruções ao modelo", "Criar embeddings manualmente", "Normalizar features"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'python', difficulty: 'medium', type: 'multiple_choice',
    question: "RLHF significa:",
    options: ["Reinforcement Learning from Human Feedback", "Regression Learning Hyper Function", "Retrieval Loss Heuristic Framework", "Random Latent Hybrid Forest"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'python', difficulty: 'medium', type: 'multiple_choice',
    question: "Fine-tuning busca:",
    options: ["Reduzir custo de SQL", "Especializar o modelo", "Balancear dados", "Criar clusters"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'python', difficulty: 'medium', type: 'multiple_choice',
    question: "Guardrails são utilizados para:",
    options: ["Aumentar dimensionalidade", "Controlar comportamento do modelo", "Criar embeddings", "Fazer joins automáticos"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'python', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual risco crítico existe em LLMs?",
    options: ["Underfitting determinístico", "Hallucination", "SQL duplication", "PCA leakage"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'python', difficulty: 'medium', type: 'multiple_choice',
    question: "Em RAG, retrieval significa:",
    options: ["Classificação supervisionada", "Recuperação de contexto", "Compressão de embeddings", "Redução de dimensionalidade"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'python', difficulty: 'medium', type: 'multiple_choice',
    question: "Busca semântica depende principalmente de:",
    options: ["Joins relacionais", "Embeddings", "Árvores de regressão", "Holdout"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'python', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual componente é essencial para RAG?",
    options: ["Banco vetorial", "GPU gráfica apenas", "SQL procedural", "K-Means"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'python', difficulty: 'medium', type: 'multiple_choice',
    question: "Embeddings permitem medir:",
    options: ["Similaridade semântica", "Apenas distância temporal", "Apenas RMSE", "Apenas cardinalidade"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'python', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual fator impacta diretamente qualidade do RAG?",
    options: ["Ordem das colunas SQL", "Qualidade da base documental", "Tipo de teclado utilizado", "Quantidade de dashboards"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'python', difficulty: 'medium', type: 'multiple_choice',
    question: "Vector database é usado para:",
    options: ["Guardar imagens rasterizadas", "Armazenar embeddings", "Criar joins automáticos", "Fazer regularização"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'python', difficulty: 'medium', type: 'multiple_choice',
    question: "Context injection em RAG significa:",
    options: ["Inserir contexto recuperado no prompt", "Remover embeddings", "Balancear classes", "Criar clusters hierárquicos"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'python', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual problema embeddings ajudam a resolver?",
    options: ["Leakage temporal", "Busca literal limitada", "Underfitting linear", "Duplicação SQL"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'python', difficulty: 'medium', type: 'multiple_choice',
    question: "RAG é especialmente útil quando:",
    options: ["Não há base documental", "É necessário grounding em dados reais", "O problema é totalmente determinístico", "Não existe contexto textual"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'python', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual componente conecta embeddings e recuperação?",
    options: ["Busca vetorial", "Random Forest", "SQL GROUP BY", "RMSE"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Clustering é:",
    options: ["Aprendizado supervisionado", "Aprendizado não supervisionado", "Regressão linear", "Método estatístico inferencial apenas"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Objetivo do clustering:",
    options: ["Prever targets", "Agrupar padrões semelhantes", "Reduzir overfitting", "Fazer joins"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "K-means utiliza:",
    options: ["Densidade probabilística temporal", "Centróides", "Árvores de decisão", "Regressão logística"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "DBSCAN é baseado em:",
    options: ["Densidade", "Probabilidade Bayesiana", "Regressão linear", "Self-attention"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual algoritmo detecta naturalmente outliers?",
    options: ["Regressão logística", "DBSCAN", "Ridge", "SQL JOIN"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Silhouette score ajuda a:",
    options: ["Medir qualidade dos clusters", "Calcular AUC", "Fazer imputação", "Balancear classes"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Elbow method auxilia na definição de:",
    options: ["Número de classes", "Número de clusters", "Número de features categóricas", "Quantidade de folds"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "GMM significa:",
    options: ["Gaussian Mixture Models", "General Metric Mapping", "Gradient Matrix Model", "Graphical Mixture Machine"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Clustering hierárquico produz:",
    options: ["Rede neural convolucional", "Estrutura em árvore", "Embeddings densos", "SQL procedural"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual risco existe ao forçar K inadequado em K-means?",
    options: ["Segmentação artificial", "Leakage temporal", "Regularização excessiva", "Underfitting supervisionado"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Programação Linear busca:",
    options: ["Encontrar solução ótima sob restrições", "Criar embeddings vetoriais", "Balancear datasets", "Fazer validação cruzada"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual problema clássico pertence à Programação Linear?",
    options: ["Transporte", "Embeddings", "RLHF", "PCA"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Simplex é:",
    options: ["Método de otimização", "Técnica de NLP", "Método de clusterização", "Métrica de classificação"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Programação Inteira utiliza:",
    options: ["Apenas variáveis contínuas", "Variáveis inteiras ou binárias", "Apenas embeddings", "Apenas probabilidades"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Branch-and-bound é utilizado em:",
    options: ["Programação inteira", "Regressão linear", "PCA", "SQL relacional"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Relaxação linear consiste em:",
    options: ["Transformar variáveis inteiras em contínuas", "Criar embeddings leves", "Reduzir dimensionalidade", "Fazer validação holdout"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "MIP significa:",
    options: ["Mixed Integer Programming", "Multi Inference Pipeline", "Matrix Interaction Process", "Maximum Information Projection"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Best Bound está associado a:",
    options: ["Solvers de otimização", "KS statistic", "Random Forest", "RAG retrieval"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual tipo de variável é comum em otimização discreta?",
    options: ["Embeddings contínuos", "Variáveis binárias", "Distância euclidiana", "Vetores normalizados"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual objetivo típico de otimização?",
    options: ["Minimizar custo ou maximizar lucro", "Criar embeddings", "Aumentar dimensionalidade", "Reduzir número de joins"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Modelos muito simples tendem a:",
    options: ["Alto variance", "Alto bias", "Alto recall apenas", "Alta dimensionalidade"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Modelos muito complexos tendem a:",
    options: ["Alto bias", "Alto variance", "Baixa capacidade", "Baixa flexibilidade"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Random Forest ajuda principalmente a reduzir:",
    options: ["Variance", "Bias apenas", "Cardinalidade", "Embeddings"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Boosting tende a reduzir:",
    options: ["Apenas dimensionalidade", "Bias", "Cardinalidade SQL", "Distância euclidiana"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Regularização excessiva pode causar:",
    options: ["Overfitting extremo", "Underfitting", "Leakage", "Drift"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Bias-variance tradeoff está relacionado a:",
    options: ["Complexidade do modelo", "Tipo de banco de dados", "Número de dashboards", "Velocidade de rede"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual cenário sugere overfitting?",
    options: ["Erro alto em treino e teste", "Performance excelente em treino e ruim em teste", "KS baixo e recall alto", "PCA bem ajustado"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual estratégia reduz overfitting?",
    options: ["Aumentar complexidade sem controle", "Regularização", "Eliminar validação", "Reduzir dados de treino drasticamente"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Underfitting normalmente produz:",
    options: ["Baixo erro apenas em treino", "Alto erro em treino e teste", "Leakage temporal", "Overfitting extremo"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual conceito mede sensibilidade do modelo aos dados?",
    options: ["Variance", "Recall", "KS", "Cardinalidade"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'data_eng', difficulty: 'medium', type: 'multiple_choice',
    question: "Drift representa:",
    options: ["Mudança no comportamento dos dados", "Redução de dimensionalidade", "Tipo de embedding", "Método de clusterização"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'data_eng', difficulty: 'medium', type: 'multiple_choice',
    question: "Model monitoring é importante para:",
    options: ["Detectar degradação em produção", "Criar joins SQL", "Balancear treino/teste", "Fazer PCA"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'data_eng', difficulty: 'medium', type: 'multiple_choice',
    question: "Rollback em ML significa:",
    options: ["Voltar versão anterior do modelo", "Criar embeddings menores", "Refazer joins", "Reiniciar GPU"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'data_eng', difficulty: 'medium', type: 'multiple_choice',
    question: "Auditabilidade exige:",
    options: ["Reprodutibilidade", "Apenas alta performance", "Apenas dashboards", "Apenas cloud computing"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'data_eng', difficulty: 'medium', type: 'multiple_choice',
    question: "Versionamento ajuda a:",
    options: ["Rastrear mudanças em modelos e dados", "Criar clusters", "Balancear classes", "Gerar embeddings"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'data_eng', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual risco existe sem governança?",
    options: ["Redução de overfitting", "Decisões inconsistentes", "Redução de drift", "Maior explicabilidade"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'data_eng', difficulty: 'medium', type: 'multiple_choice',
    question: "Pipelines automatizados ajudam principalmente em:",
    options: ["Reprodutibilidade e escala", "Apenas visualização", "Criação de embeddings manuais", "Redução de SQL"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'data_eng', difficulty: 'medium', type: 'multiple_choice',
    question: "Explicabilidade é especialmente importante em:",
    options: ["Ambientes regulados", "Jogos online", "Processos determinísticos simples", "Queries temporárias"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'data_eng', difficulty: 'medium', type: 'multiple_choice',
    question: "Data lineage permite:",
    options: ["Rastrear origem dos dados", "Criar embeddings", "Balancear clusters", "Otimizar GPU"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'data_eng', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual elemento é essencial em produção?",
    options: ["Monitoramento contínuo", "Apenas treino inicial", "Apenas dashboard final", "Apenas SQL otimizado"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'python', difficulty: 'medium', type: 'multiple_choice',
    question: "Prompt engineering influencia:",
    options: ["Qualidade das respostas do modelo", "Estrutura física do banco", "Quantidade de joins", "Distribuição normal"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'python', difficulty: 'medium', type: 'multiple_choice',
    question: "Prompts ambíguos tendem a:",
    options: ["Melhorar grounding", "Gerar respostas inconsistentes", "Reduzir hallucination", "Melhorar embeddings"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'python', difficulty: 'medium', type: 'multiple_choice',
    question: "Few-shot prompting utiliza:",
    options: ["Exemplos no contexto", "Apenas embeddings", "SQL procedural", "PCA supervisionado"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'python', difficulty: 'medium', type: 'multiple_choice',
    question: "Zero-shot prompting ocorre quando:",
    options: ["Não há exemplos fornecidos", "Há múltiplos agentes", "Há embeddings supervisionados", "Existe RLHF obrigatório"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'python', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual objetivo de guardrails?",
    options: ["Melhorar recall", "Restringir comportamento inadequado", "Balancear clusters", "Reduzir dimensionalidade"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'python', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual técnica reduz hallucination?",
    options: ["RAG", "PCA", "KNN", "GROUP BY"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'python', difficulty: 'medium', type: 'multiple_choice',
    question: "LLM sozinho tende a:",
    options: ["Sempre responder corretamente", "Alucinar sem contexto confiável", "Eliminar necessidade de dados", "Fazer validação temporal"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'python', difficulty: 'medium', type: 'multiple_choice',
    question: "Grounding significa:",
    options: ["Basear resposta em contexto real", "Balancear classes", "Reduzir variância", "Criar clusters"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'python', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual cenário justifica humano no loop?",
    options: ["Decisões críticas", "Apenas dashboards", "Processos sem risco", "PCA simples"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'python', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual fator aumenta risco operacional em IA generativa?",
    options: ["Falta de governança", "Uso de embeddings", "SQL estruturado", "Holdout simples"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual métrica é tradicionalmente relevante em crédito?",
    options: ["KS", "BLEU", "IoU", "Silhouette"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Fraude normalmente exige foco maior em:",
    options: ["Recall", "Apenas RMSE", "R²", "PCA"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Em crédito, explicabilidade é importante por:",
    options: ["Requisito regulatório", "Redução de GPU", "Aumento de embeddings", "Clusterização temporal"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Leakage em crédito pode causar:",
    options: ["Métricas artificialmente altas", "Melhor generalização real", "Menor variância obrigatoriamente", "Eliminação de drift"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual técnica é mais adequada para validação de crédito temporal?",
    options: ["Holdout aleatório", "KNN supervisionado", "Out-of-time", "One-hot encoding"],
    correct_index: 2,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Fraude frequentemente apresenta:",
    options: ["Classes balanceadas", "Desbalanceamento extremo", "Baixa dimensionalidade obrigatória", "Dados determinísticos"],
    correct_index: 1,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Outliers em fraude podem representar:",
    options: ["Sinal relevante", "Apenas erro", "Apenas ruído", "Apenas duplicação SQL"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual trade-off é comum em fraude?",
    options: ["Recall vs falso positivo", "PCA vs embeddings", "SQL vs NoSQL", "GPU vs CPU"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Threshold inadequado pode impactar:",
    options: ["Decisão operacional", "Apenas dimensionalidade", "Apenas SQL", "Apenas PCA"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual conceito é essencial para produção bancária?",
    options: ["Governança", "Apenas boosting", "Apenas embeddings", "Apenas dashboards"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual combinação reduz hallucination em LLM?",
    options: ["RAG + guardrails", "PCA + KNN", "SQL + GROUP BY", "Ridge + Lasso"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual combinação reduz overfitting?",
    options: ["Regularização + validação adequada", "Leakage + boosting", "SQL + ETL", "Embeddings + clustering"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual técnica reduz dimensionalidade preservando variância?",
    options: ["PCA", "RMSE", "KS", "JOIN"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual combinação é típica em sistemas modernos de IA generativa?",
    options: ["LLM + embeddings + RAG", "SQL + PCA + Ridge", "KNN + KS + ETL", "Random Forest + GROUP BY"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual elemento conecta ML e negócio?",
    options: ["Impacto na decisão", "Apenas algoritmo", "Apenas linguagem de programação", "Apenas banco de dados"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual cenário sugere necessidade de monitoramento contínuo?",
    options: ["Ambiente dinâmico", "Dados estáticos eternamente", "Ausência de modelos", "Problemas determinísticos simples"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual elemento é mais associado à robustez?",
    options: ["Generalização", "Cardinalidade", "SQL procedural", "Quantidade de dashboards"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual técnica ajuda a detectar degradação de dados?",
    options: ["Drift monitoring", "GROUP BY", "One-hot encoding", "K-means"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual problema surge sem separação correta de treino/teste?",
    options: ["Avaliação ilusória", "Redução de recall obrigatória", "PCA automático", "Eliminação de variância"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual conceito representa capacidade de adaptação a novos dados?",
    options: ["Generalização", "Cardinalidade", "ETL", "Drift SQL"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual algoritmo é baseado em vizinhos?",
    options: ["KNN", "Ridge", "Naive Bayes", "GLM"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual técnica mantém proporção de classes?",
    options: ["Estratificação", "PCA", "Boosting", "RLHF"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual técnica é mais indicada para explicabilidade?",
    options: ["Regressão logística", "Deep neural network profunda", "Ensemble opaco", "GMM complexo"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual métrica é usada em regressão?",
    options: ["RMSE", "KS", "Precision", "Recall"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual algoritmo é ensemble sequencial?",
    options: ["Boosting", "KNN", "PCA", "SQL JOIN"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual conceito é central em IA generativa?",
    options: ["Predição probabilística de tokens", "SQL procedural", "Árvores binárias exclusivamente", "Regressão linear simples"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual prática melhora confiabilidade de modelos?",
    options: ["Governança", "Apenas mais features", "Apenas mais GPU", "Apenas dashboards"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual conceito reduz sensibilidade a outliers?",
    options: ["Mediana", "Variância", "Recall", "AUC"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual elemento é essencial para ciência de dados aplicada?",
    options: ["Contexto de negócio", "Apenas algoritmo", "Apenas linguagem", "Apenas hardware"],
    correct_index: 0,
    explanation: '',
  },
  {
    category: 'ml', difficulty: 'medium', type: 'multiple_choice',
    question: "Qual afirmação resume melhor o objetivo da Ciência de Dados?",
    options: ["Criar modelos complexos sempre", "Transformar dados em suporte estruturado à decisão", "Automatizar toda atividade humana", "Eliminar completamente incerteza"],
    correct_index: 1,
    explanation: '',
  },

]

export function getRandomQuestions(
  count: number,
  categories?: QuestionCategory[]
): typeof LOCAL_QUESTIONS {
  let pool = categories?.length
    ? LOCAL_QUESTIONS.filter(q => categories.includes(q.category))
    : LOCAL_QUESTIONS

  // Shuffle Fisher-Yates
  const shuffled = [...pool]
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]]
  }

  return shuffled.slice(0, count)
}
